In [2]:
print("hello {name},{greeting}".format(name="ram",greeting="good morning"))

hello ram,good morning


In [5]:
print('the story of {0},{1},and {other}'.format('bill','fbhdsj',other='hus'))

the story of bill,fbhdsj,and hus


In [7]:
num=input('enter the no')
print(num)

enter the noef
ef


Bitwise operators

In [12]:
a,b=10,4  #its bitwise operation .
print(a & b)#converts to binary and multiply so o/o is 0

print (a|b)



0
14


# #Membership Operator
in and not in check

In [13]:
lst=[1,2,3,4]
print(2 in lst)

True


# To check given no is prime or not .

In [44]:
import math
num=int(input("enter the no ::"))
flag=False;
i=2;

x=math.ceil(num/2)1

while i<=x:
    if x%i==0:
        flag=True
        print("{} is divisible by{}".format(num,i))
    i+=1;
if flag:
    print("{} is not prime".format(num))
else:
    print("{} is a prime".format(num))
        
    
    
    
    

enter the no ::2
2 is a prime


In [46]:
import math
x=25
x=x/2
x=math.floor(x)
print(x)

12


# #functions  

In [50]:
def print_name(name):           
    """                              
    This function prints the sum
    """
    print("hello "+str(name))

these """ is called Doc string. this tells what fun does.
It is used for good programming practice.

To print doc string of any given function '.__doc__

In [51]:
print_name('ram')

hello ram


In [59]:
def findHCF(a,b):
    smaller=b if a>b else a
    
    hcf=1
    
    for i in range(1,smaller+1):             #since upto smaller doesnot prints the last number so smaller+1 is written.
        if(a%1==0) and (b%i==0):
            hcf=i
        return hcf
num1=94
num2=68

print("h.c.f. of {0} and {1} is:2".format(num1,num2,findHCF(num1,num2)))



h.c.f. of 94 and 68 is:2


find which is smallest. Then within range upto smallest one we have to find greatest divisible number .

# All function 

return vaue of all() function
True:if all elements in iterable are true

In [60]:
lst=[1,2,3,4,5]
print(all(lst))     #since all are none zero in lst

True


In [64]:
tuple=(0,2,3,4)    #0 present in tuple
print(all(tuple))
lst=[2,3,4,0]
print(all(lst))     #0 present in list

l=[]
print(all(l))       #empty list is always true

l=[False,1,2]
print(all(lst))    #Bool false present so



False
False
True
False


# dir()


In [65]:
num=[1,2,3,]
print(dir(num)) #all the attbs associated with datatypes list

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


if we want index aswell as values from list enumerate function is used

# filter

def pos_num(num):
    if num>0:
        return num

lst=range(-7,7)
print(list(lst))
positive_num=list(filter(pos_num,lst))

print(positive_num)

isinstance()

In [1]:
lst={1,2,3,4}
print(isinstance(lst,list))

False



# Map() 
syntax:map(function_to_apply,list_of_inputs)

In [5]:
num=[1,2,3,4,5]
#normal method to gind 1,2,69.16,25 be
squared=[]
for n in num:
    squared.append(n**2)  #appnd all the squares to squarred[] list
print(squared)

[1, 4, 9, 16, 25]


In [7]:
num=[1,2,3,4,5]
def powof2(n):
    return n**2

squared=list(map(powof2,num))
print(squared)

[1, 4, 9, 16, 25]


# reduce()
reduce fun is for performing some computation on a list and returning results
It applies rolling computation .eg[1,2,3,4] to multiply.1*2=2*3=6*4=...]

In [ ]:
#traditional method

product=1

lst=[1,2,3,4]

for num in lst:
    product*=num
print(product)

In [ ]:
from functools import reduce  #in python3 its inbuild

def mul(x,y):
    return x*y;
product=reduce(mul,lst)
print(product)

# Simple Calculator

In [1]:
def add(a,b):
    return a+b
def mul(a,b):
    return a*b
def sub(a,b):
    return a-b
def div(a,b):
    return a/b

print("enter the options")
print("1.addn")
print("2.subtrn")
print("3.multipln")
print("4.divn")

choice=int(input("enter the choice 1/2/3/4"))

num1=float(input("enter the 1st no"))

num2=float(input("enter the 2nd choice"))


if choice==1:
    print("addn of {0} and {1} is {2}".format(num1,num2,add(num1,num2)))
elif choice==2:
    print("subtrn of {0} and {1} is {2}".format(num1,num2,sub(num1,num2)))
elif choice==3:
    print("multiplication of {0} and {1} is {2}".format(num1,num2,mul(num1,num2)))
    
elif choice==4:
    print("divn of{0} and {1} is {2}".format(num1,num2,div(num1,num2)) )

else:
    print("choose within1 to 4")


enter the options
1.addn
2.subtrn
3.multipln
4.divn
enter the choice 1/2/3/44
enter the 1st no8
enter the 2nd choice2
divn of8.0 and 2.0 is 4.0


# Recursion function

factorial(3)=3*2*1=3*fact(2)
so fact(n)=n*fact(n-1)

In [11]:
def factorial(num):
    """
    this is recursive function to find the factorial of a give number
    """
    
    return 1 if num==1 else (num*factorial(num-1))

num=5
print("factorialof{0} is  {1} ".format(num,factorial(num)))


factorialof5 is  120 


# fibonacci
fib(n)=fib(n-1)+fib(n-2) #recursion

In [17]:
x=int(input("enter the no t to which fibo u want"))  #int must be define

def fibonacci(num):
    return num if num<=1 else fibonacci(num-1)+fibonacci(num-2)
print("fibo seq")
for num in range (x):
    print(fibonacci(num))

enter the no t to which fibo u want7
fibo seq
0
1
1
2
3
5
8


# Anonymous /Lambda function
these are fun  that are defined without name.
normal fun are defined usind def keywords but this has

syntax: lambda arguments:expression



In [22]:
#normal method
def double(x):
    return x*2
print(double(5))

"""
now using lambda fu"""

double=lambda x:x*2 #fun_name=lambda arg:output
print(double(5))

10
10


In [27]:
#example with filter()

lst=[1,2,3,4,5,7,90]
even_lst=list(filter(lambda x:(x%2==0), lst))
print(even_lst)

[2, 4, 90]


In [32]:
#example use with map()
lst=[1,2,3,4,5]
new_lst=list(map(lambda x: x**2,lst))
print(new_lst)


[1, 4, 9, 16, 25]


In [34]:
#example with  reduce()
from functools import reduce

lst=[1,2,3,4,5]
product_lst=reduce(lambda x,y:x*y,lst)
print(product_lst)

120


# Module

In [2]:
import math as m            #this import all math 
print(m.pi)

3.141592653589793


In [11]:
import datetime as dt  #datetime modeule
dt.datetime.now()

from math import *  #import all
print("value od pi is" +str(pi ))



value od pi is3.141592653589793


# File Handling

In [15]:
f=open('1.txt')  #by default no args=read mode
f=open('1.txt','r')
f=open('1.txt','a')  #adding new 
  #types of mode
  #  1>text_mode       #  2>bin mode  =for storing lists,matrix,vars,in scientific computaion
  #  + for both r/w
 
  #in windows text mode is 'cp1252'  in linux'utf-8'


f.close 

#this closing of file is necessary after opening because this file first loads to the ram in python then goes to hard drive . If we don't close then the file may not be saved.



Exception handline is used foe opening and closing th e file in safe way.


In [2]:
f=open("test.txt","w")
f.write("this ewill gets written in the file.if file isthere prev then new one is created by creating new one\n")
f.write("this is 2nd line of text")
f.close()

In [3]:
f=open("test.txt","r")
f.read()     #will print all content of file



'this ewill gets written in the file.if file isthere prev then new one is created by creating new one\nthis is 2nd line of text'

In [4]:
f=open("test.txt",'r')
f.read(4)  #read 4th character

'this'

now after reading 4th character the pointer points to the 4th postion then

In [5]:
f.read(4)  #this has read 4 next character from prev location . 

' ewi'

In [6]:
f.tell()  #tells current cursor location

8

In [7]:
f.seek(0)  #reset pointer to initial postion

0

In [8]:
f=open("test.txt","r")
f.read()     
f.seek(0)            #reads line by line
for line in f:
    print(line)

this ewill gets written in the file.if file isthere prev then new one is created by creating new one

this is 2nd line of text


In [33]:
f=open("test.txt","r")  #reads 1st line

In [34]:
f=open("test.txt","r")   #reads 2nd line

Renaming and deleting the fils

In [14]:
import os   #module contains osrelated functions  such  as rename delete ect

os.rename("test.txt","sample.txt")

In [17]:
f=open("sample.txt", "r")
f.readline()

'this ewill gets written in the file.if file isthere prev then new one is created by creating new one\n'

In [18]:
os.remove('sample.txt')  #deletes thee file

FOlder handling

In [19]:
import os
os.getcwd()

'/home/suprim/m_l'

In [22]:
os.listdir(os.getcwd())    #all files in current dir

['1.jpg',
 '2.jpeg',
 '.ipynb_checkpoints',
 '1.txt',
 '3.ipynb',
 'opencvbasics.ipynb']

In [23]:
os.mkdir("new")
os.rmdir('new') #removes emplty dir only


In [6]:
dir(__builtins__)   #All exceptions on python


['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [8]:
import sys  #sys is module which provide try catch etc

lst=['b',0,2]

for entry in lst:
    try:
        print("the entry is",entry)  #1st it prints
        r=1/int(entry)              #this raises an error then ASAP it goes to except block
        
    except:
        print("oops!",sys.exc_info()[0],"occured.")
        print("next entry.")
        print("*********")
print("the reciprocal of",entry,"is",r)

the entry is b
oops! <class 'ValueError'> occured.
next entry.
*********
the entry is 0
oops! <class 'ZeroDivisionError'> occured.
next entry.
*********
the entry is 2
the reciprocal of 2 is 0.5


# Raising  Exception

In [9]:
raise MemoryError("this is memo error")

MemoryError: this is memo error

# NumPY

-provids:
        1>extension packag to python for multi-D arrays
        2>closer to hardware (efficiency)
        3>designed for scientific computation(convenience)
        4>also known as array oriented computing
        

In [17]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [25]:
l=range(1000)                #without using numpy
%timeit [i**2 for i in l]   #%masures avg time per iteration

271 µs ± 4.52 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [24]:
a=np.arange(1000)
%timeit a**2

1.38 µs ± 17.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [26]:
a=np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [27]:
a.ndim

1

In [28]:
len(a)

5

In [29]:
a.shape

(5,)

Creating Numpy arrayy


In [32]:
b=np.arange(1,15,3)  #start =1, upto= 15, stepsize =3
b

array([ 1,  4,  7, 10, 13])

In [35]:
a=np.linspace(0,1,6)#start end no of points(not step size)  #linear  space  #divide 0-1 into 6 equal parts
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [36]:
np.eye(4)  #creates identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.diag([1,2,4,6])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [39]:
a=np.random.rand(4)
a

array([0.13806612, 0.5549553 , 0.26802141, 0.26517668])

In [40]:
a[1:8:2]

array([0.5549553 , 0.26517668])

In [51]:
a=np.arange(10)
a[5:]=10
a      #fifth to last chang all to 10


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [52]:
b[::-1]

array([13, 10,  7,  4,  1])

In [57]:
a=np.random.randint(0,20,15)
a

array([ 4,  6, 12,  3,  2,  6,  2, 16,  6, 10,  4, 10, 19, 18, 10])

In [58]:
mask=(a%2==0)

In [60]:
extract_from_a=a[mask]
extract_from_a  #prints only the the divisible value which gives modulo 0

array([ 4,  6, 12,  2,  6,  2, 16,  6, 10,  4, 10, 18, 10])

In [62]:
a[mask]=-1   #all even no will become -1
a

array([-1, -1, -1,  3, -1, -1, -1, -1, -1, -1, -1, -1, 19, -1, -1])

# Operations on NUMPY

In [70]:
a=np.array([1,2,3,4])
a+1           #will add 1 to all element

#calld scalar addition

array([2, 3, 4, 5])

In [71]:
a**2   #prints square

array([ 1,  4,  9, 16])

In [72]:
b=np.ones(4)+1  #2222
a-b

array([-1.,  0.,  1.,  2.])

In [74]:
a*b    #performs element wise multiplication

array([2., 4., 6., 8.])

In [76]:
x=np.arange(6)
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])